### ISSUE TITLE
EclipseMM2 doesn't work

### ISSUE THREAD

**Issue by JunkBeat** [Ethanoj1/Eclipse#11]
EclipseMM2 has been down for almost a whole day.  When I run the script, nothing happens after "fetching discord invite". 

What I tried to do to solve the problem: 
run the script using different roblox accounts through different programs (krnl, fluxus) and at different times.

Please fix, I really need this script. It would also be great if you add Eclipse Hub support for fluxus.

**Comment by Ethanoj1** [comment]
EclipseMM2 has been discontinued for over a year.
