### ISSUE TITLE
[Request] SW-M support

### ISSUE THREAD

**Issue by Thyssenkrupp234** [Ethanoj1/Eclipse#16]
For the first few weeks of Eclipse Hub, it supported SW-M. Now, SW-M doesn't have the messagebox() function which is required. Is SW-M planned to be a supported executor, and is it possible to use an alternative function for SW-M?

It's for sure not your responsibility to support almost every executor, but I think quite a few mac users would love to use the script.

Edit:

Also, when executing the old script (that works), it says something along the lines of:

> Your executor supports Eclipse Hub. Loading new script...

Which then proceeds to fail to load because of the missing messagebox() function.

If SW-M support is not planned, could the loading new script be disabled for SW-M so we can still use the old script?

Thanks!

**Comment by dhuhdw** [comment]
@Ethanoj1

**Comment by pawerpopmis** [comment]
how can i get a link in  Eclipse Hubs?

**Comment by Ethanoj1** [comment]
The use for messagebox was removed a while ago, SW-M should support.
