### ISSUE TITLE
Eclipse Hub Crashes with wave

### ISSUE THREAD

**Issue by ScripterShowcase** [Ethanoj1/Eclipse#20]
I have the latest version on wave, Eclipse Hub crashes every time I execute on any games supported by eclipse hub.
Games I tested: MM2, Be a Parkour Ninja and Natural Disaster Survival.
On every single one of those games it crashed.

Executor version and script version:
Executor: Wave
Executor Version: v2.9.1a
Hub Version: v0.98

![image](https://github.com/user-attachments/assets/6696365d-066c-4130-8b47-4a0f7fdce57a)

**Comment by Ethanoj1** [comment]
This was fixed hours after the crash started to occur, due to a bug in Wave's websocket library

**Comment by ScripterShowcase** [comment]
Hey @Ethanoj1 when I executed the script, I wanted to find the discord server. I clicked on the discord server logo that's in the script but I didn't get the invite link. Could you possibly help me with that?
