### ISSUE TITLE
Unban request

### ISSUE THREAD

**Issue by Thyssenkrupp234** [Ethanoj1/Eclipse#3]
Hey,

I was banned from the discord, and because of this I cannot use Eclipse Hub

**Executor (Please include the following):**
 - Executor: [Script-Ware M]
 - Executor Version [N/A]
 - Hub Version [N/A]

I was being childish and sent an IP logger, I have since stopped making malicious websites and wish to be unbanned so I can formally make an apology, and to use Eclipse Hub.

My discord is `thyssenkrupp234#1968`

Also, how do you make an account and request a Linker Code when the hub doesn't execute?

Thanks,

Thyssenkrupp234

**Comment by Ethanoj1** [comment]
Done
