### ISSUE TITLE
EclipseHub Premium

### ISSUE THREAD

**Issue by eclipsehubUser** [Ethanoj1/Eclipse#6]
Hello Ethanoj1 I have massive problem I bought premium for 1,500 Robux... My user is 1prodanix. So when I bought premium, I got notification that I bought and I need to go on dashboard to take new premium script. So I did that.. And than it logged out me from "EclipseHub" Site. Than I type in my email: "dgojak9@gmail.com" and password. Site said incorrect password and/or Email please try again later(or something like that). I tried to restart password and site said Error! You are requesting too fast! Try again later. I was to scared so I checked is free script changed . And I got into game and it didn't changed to premium script. Can you please check what's going on. Because I spend 1,500 Robux for that premium script.  
![My Transactions - Roblox](https://user-images.githubusercontent.com/105888640/169406000-bff63519-c663-4d24-b084-26bd961ef2f5.png)

**Comment by Ethanoj1** [comment]
Calm down, probably just a bug, DM me on discord £thanoj1#3304

**Comment by eclipsehubUser** [comment]
Can you add me danimm2#8177

**Comment by eclipsehubUser** [comment]
> Calm down, probably just a bug, DM me on discord £thanoj1#3304

What's your discord server? Because I can't add u.

**Comment by Ethanoj1** [comment]
Click the Discord icon on the Home page of Eclipse Hub.

**Comment by eclipsehubUser** [comment]
I can't it says I don't have account

**Comment by eclipsehubUser** [comment]
Please bro, I spend 1,500 Robux on premium.

**Comment by Ethanoj1** [comment]
Dude. Click the Discord Icon on Eclipse HUB, not the website.

**Comment by eclipsehubUser** [comment]
![RobloxScreenShot20220520_234047564](https://user-images.githubusercontent.com/105888640/169634081-bcc45e96-8f81-4560-996c-3dde44ddbbf6.png)
Where?

**Comment by eclipsehubUser** [comment]
I tried to click and i didn't got link

**Comment by Ethanoj1** [comment]
Click the big Discord logo right there next to your name and above your website username.

**Comment by eclipsehubUser** [comment]
nothing happened

**Comment by Ethanoj1** [comment]
Okay, log into your website account at eclipsehub.xyz, and then click the discord tab on the website.

**Comment by eclipsehubUser** [comment]
That's the problem I can't log in. And I can't restart password, website logged me out when I bought premium

**Comment by Ethanoj1** [comment]
Accept my friend request
